# Generated by Django 2.0.2 on 2018-03-09 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=45)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('title', models.CharField(editable=False, max_length=128)),
                ('username', models.CharField(max_length=32)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=4096, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\plato\\PycharmProjects\\TelegramCMS\\static\\img')),
                ('send_time', models.DateTimeField()),
                ('task_id', models.CharField(default=None, max_length=50, null=True, unique=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Channel')),
            ],
        ),
    ]
